apiVersion: v2
name: helmchecker
description: A Kubernetes CronJob that checks for outdated Helm charts and creates pull requests for updates
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://github.com/marccoxall/helmchecker
sources:
  - https://github.com/marccoxall/helmchecker
maintainers:
  - name: Marc Coxall
    email: marc@example.com
keywords:
  - helm
  - charts
  - kubernetes
  - automation
  - updates